### ISSUE TITLE
Adding Token Supply

### ISSUE THREAD

**Issue by thomivy** [Edgeware-Network/edgeware-documentation#8]
Do we have access to the token supply spreadsheet?
@dillchen

empty - https://docs.edgewa.re/edgeware-runtime/economics/token-supply-chart
yield 404 - https://edgeware-supply.now.sh/

**Comment by thomivy** [comment]
look at https://www.are.na/edgeware-community

**Comment by ShankarWarang** [comment]
I just saw that this got assigned 2 days back. Is it done already?
